# Generated by Django 4.2.2 on 2024-02-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
