# Generated by Django 4.2.2 on 2024-03-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_chatroom_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
