# Generated by Django 4.2.2 on 2024-03-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_chatroom_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-03-28 00:00:00"
            ),
            preserve_default=False,
        ),
    ]
